# Generated by Django 3.2 on 2022-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='Краткое описание поста', max_length=255, unique=True, verbose_name='Краткое описание'),
        ),
    ]
