# Generated by Django 3.2 on 2022-04-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_created_at_comment_created_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_data'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
