# Generated by Django 3.2 on 2022-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.CharField(default='Описание проекта', max_length=255, verbose_name='Описание проекта')),
                ('content', models.TextField(blank=True, verbose_name='О проекте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновелнно')),
                ('photo', models.ImageField(blank=True, upload_to='photos/my_portfolio/%Y/%m/%d/', verbose_name='Фото')),
                ('is_public', models.BooleanField(default=True, verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
