# Generated by Django 3.2 on 2022-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='link_project',
            field=models.URLField(default='Ссылка на проект', max_length=500, verbose_name='Ссылка на проект'),
        ),
    ]
