# Generated by Django 3.2 on 2022-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBanedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('attempts', models.IntegerField(default=0, verbose_name='Неудачных попыток')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Время разблокировки')),
                ('status', models.BooleanField(default=False, verbose_name='Статус блокировки')),
            ],
            options={
                'verbose_name': 'Бан по ошибкам авторизации',
                'verbose_name_plural': 'Баны по ошибкам авторизации',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='status_ban',
            field=models.BooleanField(default=False, verbose_name='Статус бана'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_ban',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки'),
        ),
    ]
